# Generated by Django 4.0.2 on 2022-04-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
