# Generated by Django 4.0.2 on 2022-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0003_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.CharField(max_length=50),
        ),
    ]
