# Generated by Django 4.0.2 on 2022-04-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_info', '0004_alter_contact_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.CharField(max_length=1000),
        ),
    ]
